[features]
strict = []

[package]
name = "example-project"
version = "0.1.3-dev"
edition = "2021"

[lib]
name = "example_project"
crate-type = ["lib", "cdylib"]


[dependencies]
c-api-tools = { path = "../" }
num = "0.4"

[build-dependencies]
cbindgen = "0.27"
